services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 256mb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
